version: '3.8'

services:
  backend:
    build: ./backend
    container_name: apitrini-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    networks:
      - apitrini-network

  frontend:
    build: ./frontend
    container_name: apitrini-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend:cached
      - /frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
      - VITE_DEV_SERVER_HOST=0.0.0.0
      - VITE_DEV_SERVER_PORT=5173
      # Nouvelles variables pour améliorer la détection des changements
      - VITE_HMR_PROTOCOL=ws
      - VITE_HMR_TIMEOUT=120000
      - NODE_ENV=development
    networks:
      - apitrini-network
    # Nous ajoutons des paramètres pour optimiser les performances
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

networks:
  apitrini-network:
    name: apitrini-network